controller:
  kind: Deployment
  replicaCount: 1
  hostNetwork: false
  service:
    externalTrafficPolicy: "Local"
    enableHttps: false
    type: "NodePort"
    nodePorts:
      http: 32082
  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
  scope:
    enabled: true
  admissionWebhooks:
    enabled: false
rbac:
  scope: true

serviceAccount:
  create: false